export const SocketEvents = {
  joinRoom: 'match:join-room',
  leaveRoom: 'match:leave-room',
  participantJoined: 'participant:joined',
  participantLeft: 'participant:left',
  participantTeamChanged: 'participant:team-changed',
  /** Legacy payload: bare slot array. Kept for compatibility; new clients use matchFormationUpdated. */
  formationUpdated: 'formation:updated',
  /** Versioned payload: FormationSnapshot ({ matchId, formationVersion, slots }). */
  matchFormationUpdated: 'match-formation:updated',
  matchStarted: 'match:started',
  matchEnded: 'match:ended',
  matchResultSubmitted: 'match:result-submitted',
  matchCompleted: 'match:completed',
  matchUpdated: 'match:updated',
  matchCancelled: 'match:cancelled',
  matchReady: 'match:ready',
  matchAvailabilityRequested: 'match-availability:requested',
  matchAvailabilityUpdated: 'match-availability:updated',
  matchLineupSelectionUpdated: 'match-lineup:selection-updated',
  matchLineupPositionOpened: 'match-lineup:position-opened',
  matchLineupPositionClaimed: 'match-lineup:position-claimed',
  matchLineupSlotMoved: 'match-lineup:slot-moved',
  matchLineupFinalized: 'match-lineup:finalized',
  matchLineupDefaultSaved: 'match-lineup:default-saved',
  sendMessage: 'message:send',
  messageCreated: 'message:created',
  directMessageSend: 'direct-message:send',
  directMessageCreated: 'direct-message:created',
  notificationCreated: 'notification:created',
  walletUpdated: 'wallet:updated',
  sessionRevoked: 'auth:session-revoked',
  teamMemberJoined: 'team:member-joined',
  teamMemberRemoved: 'team:member-removed',
  teamDetailsUpdated: 'team:details-updated',
  teamFormationUpdated: 'team:formation-updated',
  teamMemberRoleUpdated: 'team:member-role-updated',
  teamDeleted: 'team:deleted',
  teamWalletUpdated: 'team:wallet-updated',
  joinTeamRoom: 'team:join-room',
  leaveTeamRoom: 'team:leave-room',
} as const;
