export const SocketEvents = {
  joinRoom: 'match:join-room',
  leaveRoom: 'match:leave-room',
  participantJoined: 'participant:joined',
  participantLeft: 'participant:left',
  participantTeamChanged: 'participant:team-changed',
  formationUpdated: 'formation:updated',
  matchStarted: 'match:started',
  matchEnded: 'match:ended',
  matchResultSubmitted: 'match:result-submitted',
  matchCompleted: 'match:completed',
  sendMessage: 'message:send',
  messageCreated: 'message:created',
  directMessageSend: 'direct-message:send',
  directMessageCreated: 'direct-message:created',
  notificationCreated: 'notification:created',
  teamMemberJoined: 'team:member-joined',
  teamMemberRemoved: 'team:member-removed',
  teamDetailsUpdated: 'team:details-updated',
  teamFormationUpdated: 'team:formation-updated',
  joinTeamRoom: 'team:join-room',
  leaveTeamRoom: 'team:leave-room',
} as const;
