import { Router, type Router as ExpressRouter } from 'express';
import * as controller from './matches.controller.js';
export const matchesRouter: ExpressRouter = Router();
matchesRouter.get('/', controller.list);
matchesRouter.post('/', controller.create);
matchesRouter.get('/invite/:token', controller.invite);
matchesRouter.get('/:id', controller.get);
matchesRouter.patch('/:id', controller.update);
matchesRouter.delete('/:id', controller.remove);
matchesRouter.post('/:id/ready', controller.ready);
matchesRouter.post('/:id/join', controller.join);
matchesRouter.get('/:id/cancellation-quote', controller.cancellationQuote);
matchesRouter.get('/:id/cancellation-status', controller.cancellationStatus);
matchesRouter.post('/:id/leave', controller.leave);
matchesRouter.patch('/:id/formation/slots/:slotId', controller.formation);
matchesRouter.patch('/:id/participants/:participantId/team', controller.changeTeam);
matchesRouter.post('/:id/result', controller.submitResult);
matchesRouter.get('/:id/participants', controller.participants);
matchesRouter.post('/:id/team-sides/:side/availability/request', controller.requestAvailability);
matchesRouter.get('/:id/team-sides/:side/availability', controller.teamAvailability);
matchesRouter.put('/:id/team-sides/:side/availability/me', controller.updateMyAvailability);
matchesRouter.get('/:id/messages', controller.messages);
matchesRouter.post('/:id/messages', controller.sendMessage);
