ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'TEAM_MATCH_SELECTION_UPDATED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'TEAM_MATCH_POSITION_OPENED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'TEAM_MATCH_POSITION_CLAIMED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'TEAM_MATCH_LINEUP_FINALIZED';
