export const NOTIFICATION_TYPES = [
  'INFO',
  'DIRECT_MESSAGE',
  'MATCH_INVITATION',
  'DEPOSIT_SUCCEEDED',
  'MATCH_JOINED',
  'PLAYER_CANCELLED',
  'REPLACEMENT_FOUND',
  'WALLET_CREDIT',
  'MATCH_CANCELLED',
  'MATCH_STARTED',
  'RESULT_SUBMITTED',
  'TEAM_MEMBER_JOINED',
  'TEAM_UPDATED',
  'TEAM_MATCH_AVAILABILITY_REQUESTED',
  'TEAM_MATCH_SELECTION_UPDATED',
  'TEAM_MATCH_POSITION_OPENED',
  'TEAM_MATCH_POSITION_CLAIMED',
  'TEAM_MATCH_LINEUP_FINALIZED',
  'SUPPORT_REPLY',
  'BOOKING_CONFIRMED',
  'BOOKING_EXPIRED',
  'DISPUTE_RESOLVED',
  'MATCH_POSITION_CHANGED',
  'MATCH_CONFIRMED',
  'MATCH_FILL_REMINDER',
  'WALLET_DEBIT',
  // Gate 7 team matches (DEC-019).
  'TEAM_MATCH_OPPONENT_FOUND',
  'TEAM_MATCH_NO_OPPONENT_WARNING',
  'TEAM_MATCH_OPPONENT_WITHDRAWN',
  'TEAM_METER_REMINDER',
  'TEAM_CHAT_UNREAD',
  // Gate 8 (DEC-020): referee assignment notices and admin alerts.
  'REFEREE_ASSIGNED',
  'REFEREE_UNASSIGNED',
  'ADMIN_ALERT',
  'RESULT_FINAL',
  'RESULT_CORRECTED',
  'RESULT_PROBLEM_RESOLVED',
  // Gate 9 (TKT-901): friends.
  'FRIEND_REQUEST_RECEIVED',
  'FRIEND_REQUEST_ACCEPTED',
  // Gate 9 (TKT-904): personal team invites.
  'TEAM_INVITE_RECEIVED',
  'TEAM_INVITE_ANSWERED',
  // Gate 9 (TKT-909): join requests.
  'TEAM_JOIN_REQUEST_RECEIVED',
  'TEAM_JOIN_REQUEST_ANSWERED',
  // DEC-021 (batch 5): match ticketing.
  'TICKET_CHOICE_REQUIRED',
  'TICKET_REFUND_UPDATE',
  'TEAM_PAYMENT_DUE',
  'PAYMENT_DISPUTE_OPENED',
] as const;
export type NotificationType = (typeof NOTIFICATION_TYPES)[number];
export interface AppNotification {
  id: string;
  type: NotificationType;
  title: string;
  message: string;
  targetPath?: string | null;
  readAt?: string | null;
  createdAt: string;
}
