import { mkdir, unlink, writeFile } from 'node:fs/promises';
import { isAbsolute, relative, resolve } from 'node:path';

/**
 * CEO touch-up batch 3 (D2): one place where uploaded files are kept. Today the only implementation is
 * the API server's local disk (`uploads/...`). Hosts such as Render wipe that disk on every deploy or
 * restart, so before launch an S3-compatible implementation (Cloudflare R2 recommended) replaces
 * `LocalFileStorage` behind this same interface. Keys are generated by the server, never by users.
 */
export interface FileStorage {
  put(key: string, data: Buffer): Promise<void>;
  delete(key: string): Promise<void>;
  /** The absolute local path of a stored file (local disk only; used to stream private files). */
  path(key: string): string;
  /** The public URL of a file in a publicly served folder. */
  publicUrl(key: string): string;
}

const KEY = /^[0-9a-f-]{36}(-thumb)?\.(webp|png|jpg)$/i;

export class LocalFileStorage implements FileStorage {
  private readonly directory: string;
  constructor(directory: string, private readonly publicBaseUrl?: string) {
    this.directory = resolve(directory);
  }

  path(key: string) {
    if (!KEY.test(key)) throw new Error('Invalid storage key.');
    const target = resolve(this.directory, key);
    const relativeTarget = relative(this.directory, target);
    if (!relativeTarget || relativeTarget.startsWith('..') || isAbsolute(relativeTarget)) throw new Error('Invalid storage key.');
    return target;
  }

  async put(key: string, data: Buffer) {
    const target = this.path(key);
    await mkdir(this.directory, { recursive: true });
    await writeFile(target, data, { flag: 'wx' });
  }

  async delete(key: string) {
    let target: string;
    try {
      target = this.path(key);
    } catch {
      return;
    }
    await unlink(target).catch((error: NodeJS.ErrnoException) => {
      if (error.code !== 'ENOENT') throw error;
    });
  }

  publicUrl(key: string) {
    if (!this.publicBaseUrl) throw new Error('This storage folder is not public.');
    return `${this.publicBaseUrl.replace(/\/$/, '')}/${key}`;
  }

  /** The storage key of one of this folder's public URLs, or null for any other URL. */
  keyFromPublicUrl(url: string) {
    if (!this.publicBaseUrl) return null;
    const prefix = `${this.publicBaseUrl.replace(/\/$/, '')}/`;
    if (!url.startsWith(prefix)) return null;
    const key = url.slice(prefix.length);
    return KEY.test(key) ? key : null;
  }
}
