import { createServer } from 'node:http';
import { app } from './app.js';
import { env } from './config/env.js';
import { createSocketServer } from './socket/create-socket-server.js';
import { startMatchLifecycleScheduler } from './modules/matches/match-lifecycle.scheduler.js';
import { startDurableJobScheduler } from './jobs/durable-jobs.js';
import { registerWalletHoldJobHandlers } from './modules/wallet/wallet-hold.jobs.js';
import { registerBookingJobHandlers } from './modules/bookings/booking.jobs.js';
import { registerModerationJobHandlers } from './modules/moderation/moderation.jobs.js';
import { registerGoNoGoJobHandlers } from './modules/matches/go-no-go.jobs.js';
import { registerMatchCancelledEmailJobHandlers } from './modules/matches/match-cancelled-email.jobs.js';
import { registerFillReminderJobHandlers } from './modules/matches/fill-reminder.jobs.js';
import { registerTopUpJobHandlers } from './modules/payments/top-up.jobs.js';
import { registerPaystackWebhookJobHandlers } from './modules/payments/paystack-webhook.jobs.js';
import { registerTeamMatchJobHandlers } from './modules/team-matches/team-match.jobs.js';
import { registerRefereeJobHandlers } from './modules/referees/referee.jobs.js';

const server = createServer(app);
createSocketServer(server);
startMatchLifecycleScheduler();
registerWalletHoldJobHandlers();
registerBookingJobHandlers();
registerModerationJobHandlers();
registerGoNoGoJobHandlers();
registerMatchCancelledEmailJobHandlers();
registerFillReminderJobHandlers();
registerTopUpJobHandlers();
registerPaystackWebhookJobHandlers();
registerTeamMatchJobHandlers();
registerRefereeJobHandlers();
startDurableJobScheduler();
server.listen(env.PORT, () => console.log(`API listening on http://localhost:${env.PORT}`));
