ALTER TYPE "WalletTransactionType" ADD VALUE IF NOT EXISTS 'FIELD_BOOKING_DEBIT';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'BOOKING_CONFIRMED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'BOOKING_EXPIRED';
